# Generated by Django 2.2 on 2023-03-15 06:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0003_items_user_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='user_name',
            field=models.ForeignKey(default=7, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
